apiVersion: v1
kind: Service
metadata:
  name: my-backend-clusterip
  namespace: local-devops
spec:
  type: ClusterIP
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
