apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-backend-app
  namespace: argocd
spec:
  project: local-devops-project
  source:
    repoURL: https://github.com/Akash2141/local-devops.git
    targetRevision: master
    path: practice-k8s/argocd-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: local-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
