apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-devops-project
  namespace: argocd
spec:
  description: "Project for managing applications in local-devops namespace"

  destinations:
    - namespace: local-devops
      server: https://kubernetes.default.svc

  sourceRepos:
    - https://github.com/Akash2141/local-devops.git

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
