apiVersion: v1
kind: Service
metadata:
  name: my-backend-nodeport
  namespace: local-devops
spec:
  type: NodePort
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30267
