apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-backend-pod
  name: my-backend-pod
  namespace: local-devops
spec:
  containers:
    - name: my-backend
      imagePullPolicy: IfNotPresent
      image: localhost:32000/my-backend:3d19f8a38e86b2fef1d8e10e70577a0c55f8247d
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /ready-check
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /live-check
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
