version: "3.8"
services:
  nginx:
    image: my-nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pgadmin1
    networks:
      - app_network

  pgadmin1:
    image: dpage/pgadmin4:latest
    container_name: pgadmin1
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network:
