apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
  - ../../bases
patches:
  - path: patch.yaml
    target:
      kind: Deployment
configMapGenerator:
  - name: sample-backend-config
    namespace: local-devops
    behavior: merge
    env: config.properties
